name: Product Description Scraper

on:
#  push:
  workflow_dispatch:
  schedule:
    - cron:  '8 9 2,17 * *'

jobs:
  job_0:
    runs-on: ubuntu-latest 
    steps:
    - name: Check out this repo 
      uses: actions/checkout@v3
    - name: Create branch
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git checkout -b workflow_products_output_singlejob
        git push -u origin workflow_products_output_singlejob
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        ref: workflow_products_output_singlejob
    - name: Fetch latest data.
      run: |-
          chmod +x code/all_product_request.sh
          sudo ./code/all_product_request.sh
      shell: bash
    - name: Install python modules. Create master JSON.
      run: |-
        python -m pip install --upgrade pip
        pip install -r code/requirements/requirements.txt
        python code/create_master_json_and_skulist_txt.py
      shell: bash
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git branch
        git pull 
        git add json/*
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    - name: Install python modules. Upload to Autovino.
      env: 
        AUTOVINO_KEY: ${{secrets.AUTOVINO_KEY}}
      run: |-
        python -m pip install --upgrade pip
        pip install -r code/requirements/requirements.txt
        python code/updateTables.py products 
        python code/updateTables.py prices 
      shell: bash
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git config pull.rebase true
        git pull --allow-unrelated-histories origin workflow_products_output_singlejob 
        git push origin main
        git push origin --delete workflow_products_output_singlejob



